mappings:
  EmployeeDetails:
    columns:
      name:
        type: java.lang.String
        required: true
        validation: true

      salary:
        type: java.lang.String
        required: true
        validation: true
      age:
        type: java.lang.Integer
        required: false
        validation: false